### ISSUE TITLE
Treats provided images like a template

### ISSUE THREAD

**Issue by BenderNK** [RiftValleySoftware/RVS_Checkbox#1]
I love the idea and documentation of this library. Unfortunately, it didn't work for me as it appears that this library is treating the custom checkbox images as though they were templates. 

Here is my setup:
XCode 13.3
macOS 12.3.1

### Configuration
![Screen Shot 2022-04-05 at 9 39 08 AM](https://user-images.githubusercontent.com/10276667/161781687-6821b48d-48e7-4ecd-80bc-bad99d011ada.png)

### Resulting on and off state
![Screen Shot 2022-04-05 at 9 32 21 AM](https://user-images.githubusercontent.com/10276667/161781783-517a5e4a-5a1f-44c6-85d4-95ff8f65d1a6.png)
![Screen Shot 2022-04-05 at 9 32 29 AM](https://user-images.githubusercontent.com/10276667/161781806-49c20898-5af7-48f6-bf64-b0bf12f3a90e.png)

However, when using SF symbols, it appears to be working as expected. See configuration:
### SF Symbols Configuration
![Screen Shot 2022-04-05 at 9 58 46 AM](https://user-images.githubusercontent.com/10276667/161783581-1bd9a69f-858a-427c-b34f-01e0a8be49ee.png)

### Resulting on and off state
![Screen Shot 2022-04-05 at 9 59 22 AM](https://user-images.githubusercontent.com/10276667/161783895-fd6c4315-f52a-4e33-9b7a-0bbe83c7bec1.png)
![Screen Shot 2022-04-05 at 9 59 28 AM](https://user-images.githubusercontent.com/10276667/161783912-d88b6776-a7e4-484e-933b-e6059ef826bb.png)

**Comment by ChrisMarshallNY** [comment]
Sadly, they must be templates, for now. It is not optimal, but is how the project works.

I need to look at switching the project, so they use original (full-color).
